Desktop Page
igor-popov-dev/airbnb-demo-frontend pull request #1
Opened 2017-11-09 09:54 UTC by igor-popov-dev

Десктопная версия сайта

2017-11-09 15:57 UTC, evgenyrodionov commented
Не делай коммиты после запроса на ревью

2017-11-09 16:03 UTC, imevro requested changes

2017-11-09 16:03 UTC, evgenyrodionov commented on src/App.css
> +font-face {
И куда потерял @?

2017-11-09 16:03 UTC, evgenyrodionov commented on src/App.css
> +  src: url("./fonts/Circular_Air-Light.woff") format(woff),
почему у всех шрифтов один и тот же фонт-фемили? даже если ты так сделал, то почему font-weight проставлен не у всех?

https://www.webtype.com/info/articles/fonts-weights/

2017-11-09 16:03 UTC, evgenyrodionov commented on src/App.css
> +  src: url("./fonts/Circular_Air-Light.woff") format(woff),
формат должен быть в кавычках

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +} from "../Experiences/";
почему это импортится из Experiences?

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +import { Row, Title } from "../Explore/";
почему это импортится из Explore? где логика?

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +`;
ужасная адаптивность, перечитай 7 урок по вёрстке

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +`;
Почему Col2 становится на 33% и 24.9%? Если разделить 100 на 12 и умножить на 2, получится только 16

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +const Image = styled.div`
почему имейдж это див?

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +const CardItem = styled.a`
зачем постфикс айтем?

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Destinations/index.js
> +const ArrowLeft = SliderControllerLeft.extend`top: 108px;`;
чем отличается от предыдущей строчки?

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  margin-top: -12px;
отрицательные марджины зло

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  position: absolute;
вообще нет, зачем тут абсолют

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +                <li>
зачем тут списки? списки только в тексте бывают

2017-11-09 16:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +                <li className="Footer__li">
откуда тут класснейм взялся

2017-11-10 07:19 UTC, igor-popov-dev commented on src/Destinations/index.js
> +const ArrowLeft = SliderControllerLeft.extend`top: 108px;`;
левая от левой экстендится, правая от правой

2017-11-10 16:20 UTC, imevro requested changes
ОЧЕНЬ плохо с сеткой

2017-11-10 16:20 UTC, evgenyrodionov commented on src/CommonStyles.js
> +export const Col4 = styled.div`
число — это количество колонок, которые занимает элемент. Почему у тебя 4кол может занять 50%, это 6 колонок от 12?

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Destinations/index.js
> +const Col = styled.div`
лучше вообще не стало

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Destinations/index.js
> +const ImgContainer = styled.div`
что за контейнер? почему дивом?

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  SliderControllerLeft
што за контроллеры

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  SliderControllerLeft
это што за ангулар

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Experiences/index.js
> +import SectionTitle from "../SectionTitle/";
что за секшнтайтл

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Experiences/index.js
>  export const Col3 = styled.div`
а тут кто будет исправлять?

2017-11-10 16:20 UTC, evgenyrodionov commented on src/Experiences/index.js
> +        <SectionTitle name="Experiences" moreLink="ya.ru" />
что за moreLink и зачем там мусор?

2017-11-10 16:47 UTC, igor-popov-dev commented on src/Experiences/index.js
> +import SectionTitle from "../SectionTitle/";
Уже есть Title, в чате сказал- раз так, то можно оставить SectionTitle

2017-11-11 10:51 UTC, imevro requested changes

2017-11-11 10:51 UTC, evgenyrodionov commented on src/Explore/index.js
> +import { Row, Title } from "../CommonStyles.js";
зачем .джс

2017-11-11 10:51 UTC, evgenyrodionov commented on src/Footer/index.js
> +          <NavContainer>
зачем постфиксы контейнер?

2017-11-12 10:27 UTC, imevro requested changes
говорил же, не коммить после запроса ревью

в футере Nav = div? это как?
выкинь оттуда ul, к слову

2017-11-13 14:07 UTC, evgenyrodionov commented
Коммиты на английском должны быть

2017-11-13 14:07 UTC, merged

2017-11-13 14:08 UTC, evgenyrodionov commented
Делай пулл от мастера и новые бранчи от него